name: Community Contributions

on:
  pull_request:
    branches: 
    - main

jobs:
  add_to_milestone:

    if: ${{ vars.IS_PUBLIC_CONTRIB_REPO == 'true' }}
    permissions:
      pull-requests: write
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: gh pr edit ${{ github.event.number }} --milestone "Community Contributions"
